tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "autojump"
brew "bat"
brew "git"
brew "httpie"
brew "mas"
brew "n"
brew "thefuck"
cask "brave-browser"
cask "cloudflare-warp"
cask "docker"
cask "dozer"
cask "finicky"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "linear-linear"
cask "maccy"
cask "meetingbar"
cask "notion"
cask "paw"
cask "proxyman"
cask "raycast"
cask "slack"
cask "spotify"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Dato", id: 1470584107
mas "Flow", id: 1423210932
mas "Hidden Bar", id: 1452453066
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
