tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "autojump"
brew "bat"
brew "git"
brew "httpie"
brew "mas"
brew "n"
brew "thefuck"
cask "docker"
cask "dozer"
cask "finicky"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "linear-linear"
cask "maccy"
cask "meetingbar"
cask "paw"
cask "proxyman"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "Magnet", id: 441258766
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
