tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "git"
brew "bat"
brew "mas"
brew "node"
brew "httpie"
brew "autojump"
brew "thefuck"
cask "firefox"
cask "google-chrome"
cask "visual-studio-code"
cask "docker"
cask "iterm2"
cask "slack"
cask "spotify"
cask "iina"
mas "Magnet", id: 441258766
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
