# EXPORTS
export LANG="en_US.UTF-8"
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
export PATH=$PATH:/usr/local/sbin

# PROMPT SETTINGS
fpath+=("/opt/homebrew/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# COMPLETIONS
LISTMAX=300
autoload -Uz compinit; compinit
# select suggestions
zstyle ':completion:*' menu select
# case insesitive completions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# UP DOWN ARROWS SEARCH
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# HISTORY
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# OPTIONS
setopt auto_cd
zle_highlight=('paste:none')
autoload -U colors && colors

# ALIASES
alias gitclean="git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}' | xargs git branch -D"

# ADDONS
eval "$(zoxide init zsh)"
source <(fzf --zsh)

# PLUGINS
source ~/.zsh-plugins/git.zsh
source ~/.zsh-plugins/directories.zsh
source ~/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh-plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh-plugins/zsh-npm-scripts-autocomplete/zsh-npm-scripts-autocomplete.plugin.zsh

# MISE
eval "$(mise activate zsh)"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
