# EXPORTS
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
export PATH=$PATH:/usr/local/sbin

# PROMPT SETTINGS
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# COMPLETIONS
LISTMAX=300
autoload -Uz compinit; compinit
# select suggestions
zstyle ':completion:*' menu select
# case insesitive completions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# UP DOWN ARROWS SEARCH
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# OPTIONS
setopt auto_cd
unsetopt inc_append_history
unsetopt share_history
zle_highlight=('paste:none')
autoload -U colors && colors

# ALIASES
alias ls='ls -G'
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
alias gitclean="git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}' | xargs git branch -D"
alias k="kubectl"
eval $(thefuck --alias)

# ADDONS
. $(brew --prefix asdf)/libexec/asdf.sh
eval "$(zoxide init zsh)"

# PLUGINS
source ~/.zsh-plugins/git.zsh
source ~/.zsh-plugins/directories.zsh
source ~/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh-plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
